In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("advertisement .csv")
df

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0
...,...,...,...,...,...,...,...,...,...,...
995,72.97,30,71384.57,208.58,Fundamental modular algorithm,Duffystad,1,Lebanon,2016-02-11 21:49:00,1
996,51.30,45,67782.17,134.42,Grass-roots cohesive monitoring,New Darlene,1,Bosnia and Herzegovina,2016-04-22 02:07:01,1
997,51.63,51,42415.72,120.37,Expanded intangible solution,South Jessica,1,Mongolia,2016-02-01 17:24:57,1
998,55.55,19,41920.79,187.95,Proactive bandwidth-monitored policy,West Steven,0,Guatemala,2016-03-24 02:35:54,0
999,45.01,26,29875.80,178.35,Virtual 5thgeneration emulation,Ronniemouth,0,Brazil,2016-06-03 21:43:21,1

In [3]:
columns = ["daily_time_spent_on_site","age","area_income","daily_internet_usage","ad_topic_line","city","male","country","timestamp","clicked_on_ad"]

In [4]:
df.columns = columns

In [5]:
df.head()

,daily_time_spent_on_site,age,area_income,daily_internet_usage,ad_topic_line,city,male,country,timestamp,clicked_on_ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0

In [6]:
a = df["ad_topic_line"][0:100]
b = df["ad_topic_line"][100:200]
c = df["ad_topic_line"][200:300]
d = df["ad_topic_line"][300:400]
e = df["ad_topic_line"][400:500]
f = df["ad_topic_line"][500:600]
g = df["ad_topic_line"][600:700]
h = df["ad_topic_line"][700:800]
Ä± = df["ad_topic_line"][800:900]
i = df["ad_topic_line"][900: 1000]

In [7]:
df["ad_topic_line"][0:100] = d
df["ad_topic_line"][100:200] = f
df["ad_topic_line"][200:300] = c
df["ad_topic_line"][300:400] = a
df["ad_topic_line"][400:500] = e
df["ad_topic_line"][500:600] = g
df["ad_topic_line"][600:700] = Ä±
df["ad_topic_line"][700:800] = b
df["ad_topic_line"][800:900] = i
df["ad_topic_line"][900:1000] = h

<ipython-input-7-2c3c1b53072a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ad_topic_line"][0:100] = d
<ipython-input-7-2c3c1b53072a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ad_topic_line"][100:200] = f
<ipython-input-7-2c3c1b53072a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ad_topic_line"][200:300] = c
<ipython-input-7-2c3c1b53072a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ad_topic_line"][300:400] = a
<ipython-input-7-2c3c1b53072a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ad_topic_line"][400:500] = e
<ipython-input-7-2c3c1b53072a>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ad_topic_line"][500:600] = g
<ipython-input-7-2c3c1b53072a>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ad_topic_line"][600:700] = Ä±
<ipython-input-7-2c3c1b53072a>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ad_topic_line"][700:800] = b
<ipython-input-7-2c3c1b53072a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ad_topic_line"][800:900] = i
<ipython-input-7-2c3c1b53072a>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ad_topic_line"][900:1000] = h

In [8]:
a = df["city"][0:100]
b = df["city"][100:200]
c = df["city"][200:300]
d = df["city"][300:400]
e = df["city"][400:500]
f = df["city"][500:600]
g = df["city"][600:700]
h = df["city"][700:800]
Ä± = df["city"][800:900]
i = df["city"][900: 1000]

In [9]:
df["city"][0:100] = d
df["city"][100:200] = f
df["city"][200:300] = c
df["city"][300:400] = a
df["city"][400:500] = e
df["city"][500:600] = g
df["city"][600:700] = Ä±
df["city"][700:800] = b
df["city"][800:900] = i
df["city"][900:1000] = h

<ipython-input-9-d95ea9b404d7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][0:100] = d
<ipython-input-9-d95ea9b404d7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][100:200] = f
<ipython-input-9-d95ea9b404d7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][200:300] = c
<ipython-input-9-d95ea9b404d7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][300:400] = a
<ipython-input-9-d95ea9b404d7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][400:500] = e
<ipython-input-9-d95ea9b404d7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][500:600] = g
<ipython-input-9-d95ea9b404d7>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][600:700] = Ä±
<ipython-input-9-d95ea9b404d7>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][700:800] = b
<ipython-input-9-d95ea9b404d7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][800:900] = i
<ipython-input-9-d95ea9b404d7>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][900:1000] = h

In [10]:
a = df["country"][0:100]
b = df["country"][100:200]
c = df["country"][200:300]
d = df["country"][300:400]
e = df["country"][400:500]
f = df["country"][500:600]
g = df["country"][600:700]
h = df["country"][700:800]
Ä± = df["country"][800:900]
i = df["country"][900: 1000]

In [11]:
df["country"][0:100] = d
df["country"][100:200] = f
df["country"][200:300] = c
df["country"][300:400] = a
df["country"][400:500] = e
df["country"][500:600] = g
df["country"][600:700] = Ä±
df["country"][700:800] = b
df["country"][800:900] = i
df["country"][900:1000] = h

<ipython-input-11-54e414d7da8a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"][0:100] = d
<ipython-input-11-54e414d7da8a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"][100:200] = f
<ipython-input-11-54e414d7da8a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"][200:300] = c
<ipython-input-11-54e414d7da8a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"][300:400] = a
<ipython-input-11-54e414d7da8a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"][400:500] = e
<ipython-input-11-54e414d7da8a>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"][500:600] = g
<ipython-input-11-54e414d7da8a>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"][600:700] = Ä±
<ipython-input-11-54e414d7da8a>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"][700:800] = b
<ipython-input-11-54e414d7da8a>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"][800:900] = i
<ipython-input-11-54e414d7da8a>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country"][900:1000] = h

In [12]:
df.to_csv("alican.csv", index_label=False)

In [13]:
ayÅŸenur = pd.read_csv("alican.csv")
ayÅŸenur.head()

,daily_time_spent_on_site,age,area_income,daily_internet_usage,ad_topic_line,city,male,country,timestamp,clicked_on_ad
0,68.95,35,61833.90,256.09,Mandatory 3rdgeneration moderator,Cynthiaside,0,Holy See (Vatican City State),2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Enterprise-wide foreground emulation,Port Juan,1,Seychelles,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Customer-focused incremental system engine,Michellefort,0,Mayotte,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Right-sized multi-tasking solution,Port Angelamouth,1,Uganda,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Vision-oriented optimizing middleware,Jessicahaven,0,Cambodia,2016-06-03 03:36:18,0